version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu
hooks:
  Afterinstall:
    - location: nginx1.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: nginx1.sh
      timeout: 300
      runas: ubuntu

